spring:
  datasource:
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.16.18.43:1521:ims
      username: ims
      password: ims
mybatis:
  base-packages: com.exmample.dao
  type-aliases-package: com.example.dao
  mapper-locations: classpath:mapper/*.xml